run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
    - gofmt
    - gosimple

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck